name: PR checks
on:
  pull_request:
jobs:
  test:
    name: Test using JDK ${{matrix.java}} and sbt ${{matrix.sbt}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala:
          - 2.x
          - 3.x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 8
      - uses: sbt/setup-sbt@v1
      - uses: actions/cache@v4
        with:
          path: ~/.ivy2/cache
          key: ivy-${{hashFiles('**/*.sbt')}}-${{matrix.scala}}
          restore-keys: ivy-
      - uses: actions/cache@v4
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}-${{matrix.scala}}
          restore-keys: sbt-
      - run: sbt "++ ${{matrix.scala}}; test; scripted"
